import type { ListType } from '../types';

// Every user-facing string lives here. Components never inline display text.
export const strings = {
  app: { name: 'Akıllı Liste', tagline: 'Aile & Bütçe Yönetimi' },
  common: {
    cancel: 'Vazgeç',
    delete: 'Sil',
    logout: 'Çıkış yap',
    darkTheme: 'Koyu tema',
    justNow: 'Az önce',
    error: 'Bir hata oluştu',
  },
  listTypes: { SHOPPING: 'Alışveriş', TODO: 'Yapılacaklar', NOTE: 'Notlar' } as Record<
    ListType,
    string
  >,
  auth: {
    lead: 'Ailenizin listeleri ve bütçesi tek yerde.',
    namePlaceholder: 'Adınız',
    usernamePlaceholder: 'Kullanıcı adı',
    passwordPlaceholder: 'Şifre',
    register: 'Hesap oluştur',
    login: 'Giriş yap',
    haveAccount: 'Zaten hesabım var',
    newAccount: 'Yeni hesap oluştur',
    missingTitle: 'Eksik bilgi',
    missingRegister: 'Ad ve kullanıcı adı girin. Şifre en az 6 karakter olmalı.',
    missingLogin: 'Kullanıcı adı ve en az 6 karakterli şifre girin.',
    defaultFamilyName: 'Ailem',
  },
  lists: {
    title: 'Listelerim',
    lead: 'Günlük hayatınızı kolaylaştırın',
    newButton: '＋ Yeni',
    metricLists: 'Liste',
    metricNotes: 'Not',
    metricPending: 'Bekleyen',
    metricCompleted: 'Tamamlandı',
    searchPlaceholder: 'Listelerde ara...',
    emptyTitle: (typeLabel: string) => `Henüz ${typeLabel} yok`,
    emptyLead: 'İlk listenizi oluşturarak başlayın.',
    createButton: 'Liste oluştur',
    shared: '👨‍👩‍👧 Paylaşılan',
    private: '🔒 Özel',
    progress: (done: number, total: number) => `${done}/${total} tamamlandı`,
    deleteTitle: 'Listeyi sil',
    deleteMessage: (title: string) => `"${title}" silinsin mi?`,
  },
  detail: {
    sharedList: 'Paylaşılan liste',
    privateList: 'Özel liste',
    inviteTitle: 'Liste daveti',
    inviteMessage: 'Davet kodu: AILE-2026',
    titlePlaceholder: {
      SHOPPING: 'Ürün adı...',
      TODO: 'Yeni görev...',
      NOTE: 'Not başlığı...',
    } as Record<ListType, string>,
    extraPlaceholder: {
      SHOPPING: 'Miktar (örn. 2 adet)',
      TODO: 'Son tarih (isteğe bağlı)',
      NOTE: 'İçerik (isteğe bağlı)',
    } as Record<ListType, string>,
    add: 'Ekle',
    defaultQuantity: '1 adet',
    emptyTitle: 'Listeniz boş',
    emptyLead: 'İlk öğenizi yukarıdaki alandan ekleyin.',
    priority: (priority: string) => `${priority} öncelik`,
  },
  create: {
    title: 'Yeni liste oluştur',
    namePlaceholder: 'Liste adı',
    shareWithFamily: 'Ailemle paylaş',
    submit: 'Oluştur',
  },
  settings: {
    title: '⚙️ Ayarlar',
    lead: 'Hesabınızı ve tercihlerinizi yönetin.',
    edit: 'Düzenle',
    preferences: 'Tercihler',
    darkThemeLead: 'Uygulama görünümünü değiştir',
    notifications: 'Bildirimler',
    notificationsLead: 'Liste güncellemelerinden haberdar ol',
    dataManagement: 'Veri yönetimi',
    resetSample: 'Örnek verileri sıfırla',
  },
  reset: {
    title: 'Verileri sıfırla',
    message: 'Tüm yerel listeler silinsin mi?',
    confirm: 'Sıfırla',
  },
  nav: {
    lists: 'Listeler',
    finance: 'Finans',
    family: 'Ailemiz',
    analytics: 'Raporlar',
    settings: 'Ayarlar',
  },
  overview: {
    finance: {
      emoji: '💳',
      title: 'Finans',
      lead: 'Gelir, harcama ve birikimlerinizi yönetin.',
      cards: [
        ['Bu ay harcama', '₺2.450'],
        ['Aylık bütçe', '₺8.000'],
        ['Birikim', '₺12.500'],
      ],
      sectionTitle: 'Son harcamalar',
      sectionBody:
        'Henüz harcama kaydı yok. Alışveriş listenizi tamamladığınızda burada görünecek.',
    },
    family: {
      emoji: '👨‍👩‍👧',
      title: 'Ailemiz',
      lead: 'Ailenizle ortak listeleri ve üyeleri yönetin.',
      cards: [
        ['Aile adı', 'Ailem'],
        ['Üye sayısı', '3 kişi'],
        ['Paylaşılan liste', '2 liste'],
      ],
      sectionTitle: 'Aile üyeleri',
      sectionBody: 'Ayşe · Sen · Ali',
    },
    analytics: {
      emoji: '📊',
      title: 'Raporlar',
      lead: 'Harcama ve görev ilerlemenizi inceleyin.',
      cards: [
        ['Bu ay', '₺2.450'],
        ['Geçen ay', '₺1.980'],
        ['Değişim', '+%23,7'],
      ],
      sectionTitle: 'Harcama özeti',
      sectionBody: 'Market harcamaları bu ay toplamın %48’ini oluşturuyor.',
    },
  },
  seed: {
    shoppingTitle: 'Haftalık Alışveriş',
    shoppingDescription: 'Bu haftanın market ihtiyaçları',
    todosTitle: 'Ev İşleri',
    todosDescription: 'Aile olarak tamamlanacak işler',
    notesTitle: 'Fikirlerim',
    notesDescription: 'Kişisel notlar ve fikirler',
    today: 'Bugün',
    yesterday: 'Dün',
    notesDate: '12 Eyl',
    milk: 'Süt',
    eggs: 'Yumurta',
    bread: 'Ekmek',
    twoPieces: '2 adet',
    oneCarton: '1 koli',
    payBills: 'Faturaları öde',
    foldLaundry: 'Çamaşırları katla',
    weekendPlan: 'Hafta sonu planı',
    weekendPlanContent: 'Ailece parka gidilecek. Piknik sepetini hazırlamayı unutma.',
    bookIdeas: 'Kitap önerileri',
    bookIdeasContent: 'Yeni çıkan kitapları araştır.',
  },
};
