import { StyleSheet } from 'react-native';

import { colors } from '../constants/colors';

export const styles = StyleSheet.create({
  safeScreen: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background, justifyContent: 'center', padding: 20 },
  content: { padding: 20, gap: 14, backgroundColor: colors.background, flexGrow: 1 },
  headerStack: { gap: 10, marginBottom: 6 },
  centerState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, padding: 24 },
  errorCard: {
    margin: 20,
    marginTop: 32,
    padding: 20,
    borderRadius: 20,
    backgroundColor: colors.dangerSurface,
    borderWidth: 1,
    borderColor: '#fecaca',
    gap: 8,
  },
  errorTitle: { color: colors.dangerText, fontSize: 18, fontWeight: '800' },
  errorText: { color: colors.dangerText, fontSize: 14, lineHeight: 21 },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    gap: 10,
  },
  title: { color: colors.ink, fontSize: 28, fontWeight: '800', letterSpacing: -0.5 },
  subtitle: { color: colors.ink, fontSize: 17, fontWeight: '700' },
  lead: { color: colors.muted, fontSize: 14 },
  input: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    color: colors.ink,
    backgroundColor: colors.surface,
    fontSize: 16,
  },
  sectionLabel: { color: colors.muted, fontSize: 12, fontWeight: '800', letterSpacing: 0.8 },
  metricGrid: { flexDirection: 'row', gap: 10 },
  metricCard: {
    flex: 1,
    minHeight: 86,
    padding: 12,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    justifyContent: 'space-between',
  },
  metricValue: { color: colors.ink, fontSize: 18, fontWeight: '800' },
  metricLabel: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  navIcon: { fontSize: 18, lineHeight: 21 },
  chart: { gap: 12, marginTop: 8 },
  chartRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  chartLabel: { width: 74, color: colors.muted, fontSize: 11 },
  chartTrack: {
    flex: 1,
    height: 10,
    borderRadius: 6,
    backgroundColor: colors.background,
    overflow: 'hidden',
  },
  chartBar: { height: 10, borderRadius: 6, backgroundColor: colors.primary },
  chartBarEmpty: { width: 4 },
  chartBarQuarter: { width: '25%' },
  chartBarHalf: { width: '50%' },
  chartBarThreeQuarter: { width: '75%' },
  chartBarFull: { width: '100%' },
  iconBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primarySurface,
  },
  iconText: { color: colors.primaryDark, fontSize: 21, fontWeight: '800' },
  cardHeading: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  cardHeadingText: { flex: 1, gap: 4 },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
  },
  itemTitle: { flex: 1, color: colors.ink, fontSize: 15, fontWeight: '600' },
  itemCompleted: { color: colors.muted, textDecorationLine: 'line-through' },
});
