export type ListType = 'SHOPPING' | 'TODO' | 'NOTE';
export type Tab = 'lists' | 'finance' | 'family' | 'analytics' | 'settings';
export type Item = {
  id: string;
  listId?: string;
  title: string;
  content?: string;
  note?: string;
  quantity?: number;
  unit?: string;
  price?: number;
  priority?: 'LOW' | 'MEDIUM' | 'HIGH';
  dueDate?: string;
  isCompleted: boolean;
  isPinned?: boolean;
  categoryId?: string;
  assignedTo?: string;
  completedBy?: string;
  completedAt?: string;
  createdAt?: string;
};
export type AppList = {
  id: string;
  title: string;
  description?: string;
  type: ListType;
  color?: string;
  icon?: string;
  isShared: boolean;
  ownerId?: string;
  familyId?: string;
  inviteCode?: string;
  members?: Array<{ userId: string; role: string; joinedAt: string }>;
  isArchived?: boolean;
  createdAt?: string;
  updatedAt: string;
  items: Item[];
};
export type User = {
  id: string;
  name: string;
  username: string;
  email?: string;
  avatar: string;
  color?: string;
  role?: string;
  familyId?: string;
  familyName?: string;
  familyCode?: string;
  familyRole?: string;
  createdAt?: string;
};
export type FamilyMember = User;
export type Expense = {
  id: string;
  userId: string;
  familyId?: string;
  amount: number;
  currency?: string;
  categoryName: string;
  date: string;
  paymentMethod?: string;
  cardName?: string;
  note?: string;
};
export type PaymentCard = {
  id: string;
  name: string;
  type: string;
  balance: number;
  currentDebt?: number;
  creditLimit?: number;
  currency?: string;
  color?: string;
};
export type SavingsGoal = {
  id: string;
  title: string;
  currentAmount: number;
  targetAmount?: number;
  currency?: string;
};
export type PersistedState = { user: User; lists: AppList[]; dark: boolean };
